# Generated by Django 5.2 on 2025-04-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
