# Generated by Django 5.2 on 2025-04-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_remove_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
    ]
