# Generated by Django 5.2 on 2025-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0012_order_processed_by_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the employee is verified to perform certain actions.'),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_code',
            field=models.CharField(blank=True, help_text='OTP sent to customer for verification', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, help_text='Time when the OTP expires', null=True),
        ),
    ]
